### ISSUE TITLE
Add parameter to specify CDM version

### ISSUE THREAD

**Issue by mvankessel-EMC** [darwin-eu-dev/TestGenerator#5]
CDMConnector currently supports 5.3 and 5.4, but the table spec for 5.3 is currently hardcoded into the package.

**Comment by ginberg** [comment]
hi @mvankessel-EMC, that's a good point. I made a PR for it see #6 
I have set 5.3 as the default, but when I change it to 5.4 it doesn't work yet, because the [downloadEunomia](https://github.com/darwin-eu-dev/CDMConnector/blob/main/R/Eunomia.R#L30) doesn't support 5.4. Should this be adjusted @ablack3?
